pipeline:
  identifier: Build_semyonnaumov_spring_petclinic_1743064464917
  name: Build spring-petclinic
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1743064419175
        repoName: semyonnaumov/spring-petclinic
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  identifier: scalabuild
                  name: build
                  spec:
                    connectorRef: account.harnessImage
                    image: adoptopenjdk/openjdk11
                    shell: Sh
                    command: ./gradlew build
                  timeout: ""
                  type: Run
              - step:
                  identifier: scalatest
                  name: scala_test
                  spec:
                    command: ./gradlew test
                    reports:
                      spec:
                        paths:
                          - /harness/reports.xml
                      type: JUnit
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
